# Generated by Django 5.2.8 on 2025-11-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_case', models.CharField(max_length=600)),
                ('type_main_mis', models.CharField(max_length=15, null=True)),
                ('type_civil_criminal', models.CharField(max_length=15, null=True)),
                ('dist_and_session_judge', models.BooleanField(default=False)),
                ('cjm_cum_civil_judge', models.BooleanField(default=False)),
                ('civil_judge_cum_jm', models.BooleanField(default=False)),
                ('family_court', models.BooleanField(default=False)),
                ('fast_track_court', models.BooleanField(default=False)),
                ('juvenile_justice_court', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisposedCasesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('petitioner', models.CharField(max_length=1024, null=True)),
                ('responder', models.CharField(max_length=1024, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('disposed_transfered', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposed_caseses_reports_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_caseses_reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_caseses_reports_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('petitioner', models.CharField(max_length=1028, null=True)),
                ('responder', models.CharField(max_length=1028, null=True)),
                ('remarks', models.CharField(max_length=1028, null=True)),
                ('date_of_inst', models.DateField(null=True)),
                ('status', models.CharField(max_length=1028, null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldest_case', to='reports.casetype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldest_case_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldest_case', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldest_case_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_database', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PendingCasesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('case_type', models.CharField(max_length=1024, null=True)),
                ('case_type_details', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('brief_note', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_caseses_reports_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_caseses_reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_caseses_reports_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pending_start_of_month', models.IntegerField()),
                ('instituted_during_the_month', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('count_disposed_contested', models.IntegerField()),
                ('count_disposed_uncontested', models.IntegerField()),
                ('count_disposed_transferred', models.IntegerField()),
                ('pending_in_hand', models.IntegerField()),
                ('pending_more_then_2yrs', models.IntegerField()),
                ('pending_more_then_4yrs', models.IntegerField()),
                ('date_of_oldest_case', models.DateField(null=True)),
                ('unit', models.IntegerField()),
                ('no_of_working_days', models.IntegerField()),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=1500, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='reports.casetype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('case_type', 'report_year', 'report_month', 'organization')},
            },
        ),
    ]
