# Generated by Django 5.2.8 on 2025-12-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_case', to='reports.casetype'),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ex_parte_injunction_case', to='reports.casetype'),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_pending_case', to='reports.casetype'),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_case_above_sixty', to='reports.casetype'),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_case', to='reports.casetype'),
        ),
    ]
