# Generated by Django 5.2.8 on 2025-11-24 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcasesreport',
            name='case_type_details',
        ),
        migrations.AddField(
            model_name='disposedcasesreport',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pendingcasesreport',
            name='report_month',
            field=models.CharField(default=2014, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingcasesreport',
            name='report_year',
            field=models.IntegerField(default=2005),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExParteInjunctionCasesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('case_type', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('brief_note', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=1024, null=True)),
                ('duration_pending', models.IntegerField(null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expaarte_injunction_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expaarte_injunction_reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expaarte_injunction_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfUndertrialPrisoners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('prosecution', models.CharField(max_length=1024, null=True)),
                ('name_of_the_accused', models.CharField(max_length=1024, null=True)),
                ('where_about_the_accused', models.CharField(max_length=1024, null=True)),
                ('in_custody_from', models.DateField(null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_of_undertrial_prisoners', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LongPendingCasesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('case_type', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('brief_note', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=1024, null=True)),
                ('duration_pending', models.IntegerField(null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_pending_caseses_reports_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_pending_caseses_reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_pending_caseses_reports_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingCasesPartiesAboveSixty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('case_type', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('age_of_party', models.IntegerField(null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_caseses_parties_above_sixties_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_caseses_parties_above_sixties', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_caseses_parties_above_sixties_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfCourtFeesFines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('court_fees_collected', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('fines_collected', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('misc_collected', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_ment_of_court_fees_fines_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_ment_of_court_fees_fines', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_ment_of_court_fees_fines_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
