# Generated by Django 5.2.8 on 2025-12-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_disposedcasesreport_case_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='case_type',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
