# Generated by Django 5.2.8 on 2025-11-24 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0002_remove_pendingcasesreport_case_type_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disposedcasesreport',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_disposed_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='exparteinjunctioncasesreport',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_exparte_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='listofundertrialprisoners',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_under_trial_prisoner_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='longpendingcasesreport',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_long_pending_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='pendingcasespartiesabovesixty',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_pending_above_sixty_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='pendingcasesreport',
            constraint=models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_pending_case_org_year_month'),
        ),
        migrations.AddConstraint(
            model_name='statementofcourtfeesfines',
            constraint=models.UniqueConstraint(fields=('report_year', 'report_month', 'organization'), name='unique_court_fees_org_year_month'),
        ),
    ]
