# Generated by Django 5.2.8 on 2025-12-08 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0004_listofundertrialprisoners_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesUnderVulnerableGroupCasesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inst', models.DateField(null=True)),
                ('case_no', models.CharField(max_length=50, null=True)),
                ('case_title', models.CharField(max_length=1024, null=True)),
                ('case_type', models.CharField(max_length=1024, null=True)),
                ('civil_criminal', models.CharField(max_length=50, null=True)),
                ('brief_note', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=1024, null=True)),
                ('vulnerable_group', models.CharField(max_length=255, null=True)),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_under_vulnerable_group_reports_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_under_vulnerable_group_reports', to='accounts.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_under_vulnerable_group_reports_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case_no', 'report_year', 'report_month', 'organization'), name='unique_vulnerable_group_case_org_year_month')],
            },
        ),
    ]
