# Generated by Django 5.2.8 on 2025-12-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_partiesundervulnerablegroupcasesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedcasesreport',
            name='date_of_decision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposedcasesreport',
            name='goshwara_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposedcasesreport',
            name='transfer_est',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
