# Generated by Django 5.2.8 on 2025-12-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_disposedcasesreport_date_of_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='date_of_decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='disposed_transfered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='goshwara_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='petitioner',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='responder',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='transfer_est',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
