# Generated by Django 5.2.8 on 2025-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_disposedcasesreport_case_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedcasesreport',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='brief_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='duration_pending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exparteinjunctioncasesreport',
            name='status',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='in_custody_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='name_of_the_accused',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='prosecution',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofundertrialprisoners',
            name='where_about_the_accused',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='brief_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='duration_pending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='longpendingcasesreport',
            name='status',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='brief_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='status',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partiesundervulnerablegroupcasesreport',
            name='vulnerable_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='age_of_party',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasespartiesabovesixty',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='brief_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='case_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='case_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='civil_criminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='date_of_inst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcasesreport',
            name='status',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statementofcourtfeesfines',
            name='court_fees_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='statementofcourtfeesfines',
            name='fines_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='statementofcourtfeesfines',
            name='misc_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='statementofcourtfeesfines',
            name='report_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
