# Generated by Django 5.2.8 on 2025-12-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_disposedcasesreport_report_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='organisation',
        ),
    ]
